# Generated by Django 4.2.4 on 2024-12-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("services", "0001_initial"),
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="services",
            field=models.ManyToManyField(
                blank=True, related_name="customers", to="services.services"
            ),
        ),
    ]
