# Generated by Django 5.1.2 on 2025-01-09 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_department_customer_departments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Polygon',
        ),
    ]
