# Generated by Django 5.1.2 on 2025-01-10 15:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamimage',
            name='fulladdress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='streamimage',
            name='lang',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='streamimage',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='streamimage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='streamimage',
            name='processed',
            field=models.BooleanField(default=True),
        ),
    ]
