# Generated by Django 5.1.2 on 2025-01-26 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_remove_notifications_customer_and_more'),
        ('stream', '0002_remove_detection_x_coord_remove_detection_y_coord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='notification.notification'),
        ),
    ]
