# Generated by Django 5.1.2 on 2025-01-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_streamimage_fulladdress_streamimage_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamimage',
            name='uuid',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
