# Generated by Django 5.1.2 on 2025-01-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0004_remove_streamimage_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamimage',
            name='device_uuid',
            field=models.UUIDField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
