# Generated by Django 5.1.2 on 2025-01-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0005_streamimage_device_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamimage',
            name='device_uuid',
        ),
        migrations.AddField(
            model_name='streamimage',
            name='deviceuuid',
            field=models.CharField(default=1, editable=False, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
