# Generated by Django 5.1.2 on 2025-01-22 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0008_remove_streamimage_image_processing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='stream.streamimage'),
        ),
    ]
