# Generated by Django 5.1.2 on 2025-01-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0009_alter_detection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamimage',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
