# Generated by Django 4.2.4 on 2024-12-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_reports"),
    ]

    operations = [
        migrations.AddField(
            model_name="reports",
            name="captured_image",
            field=models.ImageField(blank=True, null=True, upload_to="reports/images/"),
        ),
        migrations.AddField(
            model_name="reports",
            name="video_clip",
            field=models.FileField(blank=True, null=True, upload_to="reports/videos/"),
        ),
    ]
