# Generated by Django 4.2.4 on 2024-12-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_reports_captured_image_reports_video_clip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sources",
            name="status",
            field=models.CharField(blank=True, default="0", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="sources",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HLS", "HTTP Live Streaming (HLS)"),
                    ("MPEG-DASH", "MPEG-DASH"),
                    ("LOCAL_FILES", "Local Files"),
                    ("NETWORK_STREAMS", "Network Streams"),
                    ("WEBCAMS", "Webcams"),
                    ("IP_CAMERAS", "IP Cameras"),
                    ("VIDEO_FILE_HOSTING", "Video File Hosting Services"),
                ],
                default="RTSP",
                max_length=50,
                null=True,
            ),
        ),
    ]
