# Generated by Django 4.2.4 on 2024-12-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0004_alter_sources_status_alter_sources_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sources",
            name="type",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
