# Generated by Django 4.2.4 on 2024-12-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0005_alter_sources_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sources",
            name="inlocation",
        ),
        migrations.AddField(
            model_name="sources",
            name="bitrate",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sources",
            name="codec",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
