# Generated by Django 4.2.4 on 2024-12-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0006_remove_sources_inlocation_sources_bitrate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sources",
            name="duration",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="sources",
            name="total_frames",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="sources",
            name="codec",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="sources",
            name="height",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="sources",
            name="width",
            field=models.IntegerField(null=True),
        ),
    ]
