# Generated by Django 4.2.4 on 2024-12-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0007_sources_duration_sources_total_frames_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sources",
            name="bitrate",
        ),
        migrations.RemoveField(
            model_name="sources",
            name="codec",
        ),
        migrations.RemoveField(
            model_name="sources",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="sources",
            name="total_frames",
        ),
        migrations.AddField(
            model_name="sources",
            name="inlocation",
            field=models.ManyToManyField(
                blank=True, related_name="sources", to="services.location"
            ),
        ),
        migrations.AlterField(
            model_name="sources",
            name="height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sources",
            name="width",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
