# Generated by Django 4.2.4 on 2024-12-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0008_remove_sources_bitrate_remove_sources_codec_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sources",
            name="codec",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="sources",
            name="total_frames",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
