# Generated by Django 4.2.4 on 2024-12-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0009_sources_codec_sources_total_frames"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rulesadd",
            name="polygon",
        ),
        migrations.AddField(
            model_name="sources",
            name="crossing_direction",
            field=models.JSONField(
                blank=True,
                help_text="Store direction for each transition line as ['left-to-right', 'right-to-left', ...]",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sources",
            name="polygons",
            field=models.JSONField(
                default=1, help_text="Store coordinates as [[x1,y1], [x2,y2],...]"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sources",
            name="polygons_color",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sources",
            name="polygons_label",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sources",
            name="transition_lines",
            field=models.JSONField(
                blank=True,
                help_text="Store transition lines as [[[x1,y1], [x2,y2]], [[x3,y3], [x4,y4]], ...]",
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="Polygons",
        ),
    ]
