# Generated by Django 4.2.4 on 2024-12-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "services",
            "0010_remove_rulesadd_polygon_sources_crossing_direction_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sources",
            name="crossing_direction",
        ),
        migrations.RemoveField(
            model_name="sources",
            name="polygons_color",
        ),
        migrations.RemoveField(
            model_name="sources",
            name="polygons_label",
        ),
        migrations.RemoveField(
            model_name="sources",
            name="transition_lines",
        ),
        migrations.AlterField(
            model_name="sources",
            name="polygons",
            field=models.JSONField(
                blank=True,
                help_text="Store polygon data as list of objects: [{coordinates: [[x1,y1], [x2,y2],...], label: 'string', color: 'string', transition_lines: [[[x1,y1], [x2,y2]], ...], crossing_direction: ['left-to-right', ...]}]",
                null=True,
            ),
        ),
    ]
