# Generated by Django 5.1.2 on 2025-01-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_remove_sources_crossing_direction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='rules/icons/')),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='reports',
            name='rules',
        ),
        migrations.DeleteModel(
            name='RulesAdd',
        ),
    ]
