# Generated by Django 5.1.2 on 2025-01-26 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_remove_notifications_customer_and_more'),
        ('services', '0012_ruleslist_remove_reports_rules_delete_rulesadd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='notifications',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='notification.notification'),
        ),
    ]
