# Generated by Django 5.1.2 on 2025-01-27 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('council', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('REPORT_ONLY', 'Sadece Raporla'), ('DEPARTMENT_NOTIFY', 'Departmana Bildir'), ('PERSON_NOTIFY', 'Kişiye Bildir'), ('SMS', 'SMS Gönder'), ('EMAIL', 'E-posta Gönder'), ('WHATSAPP', 'WhatsApp Gönder')], max_length=20)),
                ('description', models.CharField(max_length=255, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Bildirim Kanalı',
                'verbose_name_plural': 'Bildirim Kanalları',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(default='Varsayılan Kural', max_length=255, verbose_name='Kural Adı')),
                ('title', models.CharField(default='Varsayılan Kural', help_text='Bu kuralın tanımlayıcı adı', max_length=255, verbose_name='Kural Adı')),
                ('type', models.CharField(choices=[('REPORT_ONLY', 'Sadece Raporla'), ('DEPARTMENT_NOTIFY', 'Departmana Bildir'), ('PERSON_NOTIFY', 'Kişiye Bildir'), ('SMS', 'SMS Gönder'), ('EMAIL', 'E-posta Gönder'), ('WHATSAPP', 'WhatsApp Gönder')], default='REPORT_ONLY', max_length=20)),
                ('message', models.TextField()),
                ('class_field', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('notification_history', models.JSONField(blank=True, default=list)),
                ('severity', models.CharField(choices=[('LOW', 'Düşük'), ('MEDIUM', 'Orta'), ('HIGH', 'Yüksek'), ('CRITICAL', 'Kritik')], default='MEDIUM', max_length=10, verbose_name='Uyarı Düzeyi')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='council.department')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('channels', models.ManyToManyField(help_text='Birden fazla kanal seçebilirsiniz', to='notification.notificationchannel', verbose_name='Bildirim Kanalları')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='SMTP Sunucu')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='SMTP Port')),
                ('smtp_user', models.CharField(default='user@algi.ai', max_length=255, verbose_name='SMTP Kullanıcı')),
                ('smtp_password', models.CharField(default='default_password', max_length=255, verbose_name='SMTP Şifre')),
                ('from_email', models.EmailField(default='notifications@algi.ai', max_length=254, verbose_name='Gönderen E-posta')),
                ('email_template', models.TextField(blank=True, null=True, verbose_name='E-posta Şablonu')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mail_settings', to='notification.notification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_key', models.CharField(max_length=255, verbose_name='Uygulama Anahtarı')),
                ('app_secret', models.CharField(max_length=255, verbose_name='Uygulama Gizli Anahtarı')),
                ('device_token', models.TextField(verbose_name='Cihaz Token')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='push_settings', to='notification.notification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SmsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.CharField(default='default_api_key', max_length=255, verbose_name='API Anahtarı')),
                ('api_secret', models.CharField(default='default_api_secret', max_length=255, verbose_name='API Gizli Anahtarı')),
                ('sender_name', models.CharField(default='ALGI', max_length=11, verbose_name='Gönderen Adı')),
                ('api_endpoint', models.URLField(default='https://api.example.com', verbose_name='API Endpoint')),
                ('sms_template', models.TextField(blank=True, null=True, verbose_name='SMS Şablonu')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_settings', to='notification.notification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhatsappSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wa_api_key', models.CharField(default='default_wa_api_key', max_length=255, verbose_name='WhatsApp API Anahtarı')),
                ('wa_api_secret', models.CharField(default='default_wa_secret', max_length=255, verbose_name='WhatsApp API Gizli Anahtarı')),
                ('wa_phone_number', models.CharField(default='+905555555555', max_length=15, verbose_name='WhatsApp Telefon No')),
                ('wa_api_endpoint', models.URLField(default='https://api.whatsapp.com', verbose_name='WhatsApp API Endpoint')),
                ('whatsapp_template', models.TextField(blank=True, null=True, verbose_name='WhatsApp Şablonu')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_settings', to='notification.notification')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
