# Generated by Django 5.1.2 on 2025-01-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='rule_name',
            field=models.CharField(default=1, help_text='Bu kuralın tanımlayıcı adı', max_length=255, verbose_name='Kural Adı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Düşük'), ('MEDIUM', 'Orta'), ('HIGH', 'Yüksek'), ('CRITICAL', 'Kritik')], default='MEDIUM', max_length=10, verbose_name='Uyarı Düzeyi'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('REPORT_ONLY', 'Sadece Raporla'), ('DEPARTMENT_NOTIFY', 'Departmana Bildir'), ('PERSON_NOTIFY', 'Kişiye Bildir'), ('SMS', 'SMS Gönder'), ('EMAIL', 'E-posta Gönder'), ('WHATSAPP', 'WhatsApp Gönder')], default='REPORT_ONLY', max_length=20),
        ),
    ]
