# Generated by Django 4.2.4 on 2024-12-15 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("whatsapp", models.BooleanField(default=False)),
                ("mail", models.BooleanField(default=False)),
                ("sms", models.BooleanField(default=False)),
                ("push", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="notifications",
            name="mail",
        ),
        migrations.RemoveField(
            model_name="notifications",
            name="push",
        ),
        migrations.RemoveField(
            model_name="notifications",
            name="sms",
        ),
        migrations.RemoveField(
            model_name="notifications",
            name="whatsapp",
        ),
        migrations.AddField(
            model_name="notifications",
            name="settings",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification",
                to="notification.notificationsettings",
            ),
            preserve_default=False,
        ),
    ]
