# Generated by Django 5.1.2 on 2025-01-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_rule_name_notification_severity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='rule_name',
            field=models.CharField(blank=True, help_text='Bu kuralın tanımlayıcı adı', max_length=255, null=True, verbose_name='Kural Adı'),
        ),
    ]
