# Generated by Django 4.2.4 on 2024-12-15 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "notification",
            "0002_notificationsettings_remove_notifications_mail_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MailSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("smtp_server", models.CharField(max_length=255)),
                ("smtp_port", models.IntegerField()),
                ("smtp_user", models.CharField(max_length=255)),
                ("smtp_password", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SmsSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("netgsm_user", models.CharField(max_length=255)),
                ("netgsm_password", models.CharField(max_length=255)),
                ("netgsm_header", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="WhatsappSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facebook_app_id", models.CharField(max_length=255)),
                ("facebook_app_secret", models.CharField(max_length=255)),
                ("facebook_access_token", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="notifications",
            name="mail_settings",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification",
                to="notification.mailsettings",
            ),
        ),
        migrations.AddField(
            model_name="notifications",
            name="sms_settings",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification",
                to="notification.smssettings",
            ),
        ),
        migrations.AddField(
            model_name="notifications",
            name="whatsapp_settings",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification",
                to="notification.whatsappsettings",
            ),
        ),
    ]
