# Generated by Django 5.1.2 on 2025-01-27 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_remove_notificationchannel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushnotification',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='smssettings',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='whatsappsettings',
            name='notification',
        ),
        migrations.DeleteModel(
            name='MailSettings',
        ),
        migrations.DeleteModel(
            name='PushNotification',
        ),
        migrations.DeleteModel(
            name='SmsSettings',
        ),
        migrations.DeleteModel(
            name='WhatsappSettings',
        ),
    ]
