# Generated by Django 4.2.4 on 2024-12-15 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0003_mailsettings_smssettings_whatsappsettings_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notifications",
            name="mail_settings",
        ),
        migrations.RemoveField(
            model_name="notifications",
            name="settings",
        ),
        migrations.RemoveField(
            model_name="notifications",
            name="sms_settings",
        ),
        migrations.RemoveField(
            model_name="notifications",
            name="whatsapp_settings",
        ),
        migrations.AddField(
            model_name="mailsettings",
            name="notification",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mail_settings",
                to="notification.notifications",
            ),
        ),
        migrations.AddField(
            model_name="notificationsettings",
            name="notification",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_settings",
                to="notification.notifications",
            ),
        ),
        migrations.AddField(
            model_name="smssettings",
            name="notification",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sms_settings",
                to="notification.notifications",
            ),
        ),
        migrations.AddField(
            model_name="whatsappsettings",
            name="notification",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="whatsapp_settings",
                to="notification.notifications",
            ),
        ),
    ]
