# Generated by Django 5.1.2 on 2025-01-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_rule_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_key', models.CharField(max_length=255, verbose_name='Uygulama Anahtarı')),
                ('app_secret', models.CharField(max_length=255, verbose_name='Uygulama Gizli Anahtarı')),
                ('device_token', models.TextField(help_text="Push notification gönderilecek cihaz token'ı", verbose_name='Cihaz Token')),
            ],
            options={
                'verbose_name': 'Push Notification Ayarları',
                'verbose_name_plural': 'Push Notification Ayarları',
            },
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.AddField(
            model_name='mailsettings',
            name='from_email',
            field=models.EmailField(default='notifications@algi.ai', max_length=254, verbose_name='Gönderen E-posta'),
        ),
        migrations.AddField(
            model_name='mailsettings',
            name='smtp_host',
            field=models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='SMTP Sunucu'),
        ),
        migrations.AddField(
            model_name='mailsettings',
            name='smtp_password',
            field=models.CharField(default='default_password', max_length=255, verbose_name='SMTP Şifre'),
        ),
        migrations.AddField(
            model_name='mailsettings',
            name='smtp_port',
            field=models.IntegerField(default=587, verbose_name='SMTP Port'),
        ),
        migrations.AddField(
            model_name='mailsettings',
            name='smtp_user',
            field=models.CharField(default='user@algi.ai', max_length=255, verbose_name='SMTP Kullanıcı'),
        ),
        migrations.AddField(
            model_name='smssettings',
            name='api_endpoint',
            field=models.URLField(default='https://api.example.com', verbose_name='API Endpoint'),
        ),
        migrations.AddField(
            model_name='smssettings',
            name='api_key',
            field=models.CharField(default='default_api_key', max_length=255, verbose_name='API Anahtarı'),
        ),
        migrations.AddField(
            model_name='smssettings',
            name='api_secret',
            field=models.CharField(default='default_api_secret', max_length=255, verbose_name='API Gizli Anahtarı'),
        ),
        migrations.AddField(
            model_name='smssettings',
            name='sender_name',
            field=models.CharField(default='ALGI', max_length=11, verbose_name='Gönderen Adı'),
        ),
        migrations.AddField(
            model_name='whatsappsettings',
            name='wa_api_endpoint',
            field=models.URLField(default='https://api.whatsapp.com', verbose_name='WhatsApp API Endpoint'),
        ),
        migrations.AddField(
            model_name='whatsappsettings',
            name='wa_api_key',
            field=models.CharField(default='default_wa_api_key', max_length=255, verbose_name='WhatsApp API Anahtarı'),
        ),
        migrations.AddField(
            model_name='whatsappsettings',
            name='wa_api_secret',
            field=models.CharField(default='default_wa_secret', max_length=255, verbose_name='WhatsApp API Gizli Anahtarı'),
        ),
        migrations.AddField(
            model_name='whatsappsettings',
            name='wa_phone_number',
            field=models.CharField(default='+905555555555', max_length=15, verbose_name='WhatsApp Telefon No'),
        ),
        migrations.AlterField(
            model_name='mailsettings',
            name='email_template',
            field=models.TextField(blank=True, null=True, verbose_name='E-posta Şablonu'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='rule_name',
            field=models.CharField(default='Varsayılan Kural', help_text='Bu kuralın tanımlayıcı adı', max_length=255, verbose_name='Kural Adı'),
        ),
        migrations.AlterField(
            model_name='smssettings',
            name='sms_template',
            field=models.TextField(blank=True, null=True, verbose_name='SMS Şablonu'),
        ),
        migrations.AlterField(
            model_name='whatsappsettings',
            name='whatsapp_template',
            field=models.TextField(blank=True, null=True, verbose_name='WhatsApp Şablonu'),
        ),
    ]
