# Generated by Django 5.1.2 on 2025-01-26 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_remove_notifications_mail_settings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mailsettings',
            name='smtp_password',
        ),
        migrations.RemoveField(
            model_name='mailsettings',
            name='smtp_port',
        ),
        migrations.RemoveField(
            model_name='mailsettings',
            name='smtp_server',
        ),
        migrations.RemoveField(
            model_name='mailsettings',
            name='smtp_user',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='push',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='sms',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='smssettings',
            name='netgsm_header',
        ),
        migrations.RemoveField(
            model_name='smssettings',
            name='netgsm_password',
        ),
        migrations.RemoveField(
            model_name='smssettings',
            name='netgsm_user',
        ),
        migrations.RemoveField(
            model_name='whatsappsettings',
            name='facebook_access_token',
        ),
        migrations.RemoveField(
            model_name='whatsappsettings',
            name='facebook_app_id',
        ),
        migrations.RemoveField(
            model_name='whatsappsettings',
            name='facebook_app_secret',
        ),
        migrations.AddField(
            model_name='mailsettings',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='smssettings',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappsettings',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='mailsettings',
            name='notification',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mail_settings', to='notification.notification'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='notification',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='notification.notification'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='smssettings',
            name='notification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_settings', to='notification.notification'),
        ),
        migrations.AlterField(
            model_name='whatsappsettings',
            name='notification',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_settings', to='notification.notification'),
            preserve_default=False,
        ),
    ]
