# Generated by Django 5.1.2 on 2025-01-27 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_pushnotification_remove_notification_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='rule_name',
            new_name='title',
        ),
    ]
