# Generated by Django 5.1.2 on 2025-01-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_remove_notifications_customer_and_more'),
        ('services', '0013_alter_reports_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
