# Generated by Django 5.1.2 on 2025-01-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_delete_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='class_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
