# Generated by Django 5.1.2 on 2025-01-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_notification_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_history',
            field=models.JSONField(blank=True, default=list, help_text='\n        Stores history of sent notifications in format:\n        [{\n            "id": "uuid",\n            "timestamp": "iso-date",\n            "status": "sent|delivered|failed",\n            "channel": "sms|email|whatsapp",\n            "recipient": "user/number/email",\n            "error": "error message if failed"\n        }]\n    '),
        ),
    ]
