# Generated by Django 5.1.2 on 2025-01-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Way',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way_id', models.BigIntegerField()),
                ('nodes', models.JSONField()),
                ('highway', models.CharField(max_length=50)),
                ('lanes', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('oneway', models.BooleanField()),
                ('ref', models.CharField(max_length=20)),
            ],
        ),
    ]
