# Generated by Django 5.1.2 on 2025-01-26 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Way',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_type', models.CharField(max_length=50)),
                ('way_id', models.IntegerField(unique=True)),
                ('nodes', models.JSONField()),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('highway', models.CharField(max_length=50)),
                ('hist_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('loc_name', models.CharField(blank=True, max_length=50, null=True)),
                ('maxspeed', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(max_length=255)),
                ('oneway', models.CharField(max_length=10)),
                ('ref', models.CharField(max_length=50)),
                ('lanes', models.CharField(blank=True, max_length=10, null=True)),
                ('nat_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('toll', models.CharField(blank=True, max_length=10, null=True)),
                ('tracker_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='council_departments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
