# Generated by Django 5.1.2 on 2025-01-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0002_department_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='way',
            name='lanes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='way',
            name='ref',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='way',
            name='way_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
