# Generated by Django 5.1.2 on 2025-01-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0003_alter_way_lanes_alter_way_ref_alter_way_way_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='way',
            name='nodes',
            field=models.TextField(),
        ),
    ]
