# Generated by Django 5.1.2 on 2025-01-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0006_way_tags_alter_way_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='way',
            name='lanes',
        ),
        migrations.RemoveField(
            model_name='way',
            name='tags',
        ),
        migrations.AddField(
            model_name='way',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='way',
            name='hist_ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='way',
            name='loc_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='way',
            name='maxspeed',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='way',
            name='highway',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='way',
            name='nodes',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='way',
            name='way_id',
            field=models.BigIntegerField(),
        ),
    ]
