# Generated by Django 5.1.2 on 2025-01-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0007_remove_way_lanes_remove_way_tags_way_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='way',
            name='tags',
            field=models.JSONField(default=dict),
        ),
    ]
