# Generated by Django 5.1.2 on 2025-01-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0008_way_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='way',
            name='tags',
        ),
        migrations.AddField(
            model_name='way',
            name='lanes',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='way',
            name='nat_ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='way',
            name='toll',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='way',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='way',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='way',
            name='loc_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='way',
            name='maxspeed',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='way',
            name='oneway',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
