# Generated by Django 5.1.2 on 2025-01-20 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0009_remove_way_tags_way_lanes_way_nat_ref_way_toll_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='way',
            old_name='type',
            new_name='base_type',
        ),
    ]
