# Generated by Django 5.1.2 on 2025-01-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0010_rename_type_way_base_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='way',
            name='base_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='way',
            name='highway',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='way',
            name='lanes',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='way',
            name='maxspeed',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='way',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='way',
            name='oneway',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='way',
            name='ref',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='way',
            name='toll',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='way',
            name='way_id',
            field=models.IntegerField(unique=True),
        ),
    ]
