# Generated by Django 5.1.2 on 2025-01-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0012_alter_department_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='way',
            name='tracker_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
