# Generated by Django 5.1.2 on 2025-01-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_alter_streamimage_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamimage',
            name='uuid',
        ),
    ]
