# Generated by Django 5.1.2 on 2025-01-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0006_remove_streamimage_device_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamimage',
            name='image_processing',
            field=models.ImageField(blank=True, null=True, upload_to='stream_images/'),
        ),
        migrations.AlterField(
            model_name='streamimage',
            name='deviceuuid',
            field=models.CharField(max_length=255),
        ),
    ]
