# Generated by Django 5.1.2 on 2025-01-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0007_streamimage_image_processing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamimage',
            name='image_processing',
        ),
        migrations.AlterField(
            model_name='streamimage',
            name='deviceuuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='streamimage',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
